export type View =
  | "landing"
  | "dashboard"
  | "add-pet"
  | "owner-pet-detail"
  | "staff-pet-detail"
  | "staff-search"

export interface Vaccine {
  name: string
  date: string
  vetId: string
  status: "Vigente" | "Vencida"
}

export interface Pet {
  id: string
  name: string
  species: string
  breed: string
  sex: string
  birthDate: string
  age: string
  microchip: string
  location: string
  imageUrl: string
  isServiceAnimal: boolean
  isSterilized: boolean
  healthStatus: string
  allergies: string
  medications: string
  diseases: string[]
  vaccines: Vaccine[]
  foodMain: string
  dietType: string
  dailyAmount: string
  activityLevel: string
  coexistsWithOtherPets: boolean
}

export const petDatabase: Pet[] = [
  {
    id: "1",
    name: "Champeta",
    species: "Perro",
    breed: "Caniche Miniatura",
    sex: "Macho",
    birthDate: "15/03/2019",
    age: "7 anos",
    microchip: "985112003476521",
    location: "Cartagena, Colombia",
    imageUrl: "/images/champeta-dog.jpg",
    isServiceAnimal: false,
    isSterilized: true,
    healthStatus: "Saludable",
    allergies: "Polen, acaros del polvo",
    medications: "Meloxicam 5mg cada 12h (temporal)",
    diseases: ["Artritis"],
    vaccines: [
      { name: "Rabia", date: "10/01/2025", vetId: "VET-84729", status: "Vigente" },
      { name: "Parvovirus", date: "15/06/2024", vetId: "VET-84729", status: "Vigente" },
      { name: "Moquillo", date: "15/06/2024", vetId: "VET-31205", status: "Vigente" },
      { name: "Leptospirosis", date: "20/03/2023", vetId: "VET-31205", status: "Vencida" },
    ],
    foodMain: "Royal Canin Mini Adult",
    dietType: "Pienso / Croquetas",
    dailyAmount: "1.5 tazas (120g)",
    activityLevel: "Medio",
    coexistsWithOtherPets: true,
  },
  {
    id: "2",
    name: "Luna",
    species: "Gato",
    breed: "Siames",
    sex: "Hembra",
    birthDate: "22/08/2023",
    age: "3 anos",
    microchip: "985112007834210",
    location: "Bogota, Colombia",
    imageUrl: "/images/luna-cat.jpg",
    isServiceAnimal: false,
    isSterilized: true,
    healthStatus: "Saludable",
    allergies: "Ninguna conocida",
    medications: "Ninguno",
    diseases: [],
    vaccines: [
      { name: "Triple Felina", date: "05/09/2025", vetId: "VET-56102", status: "Vigente" },
      { name: "Rabia", date: "05/09/2025", vetId: "VET-56102", status: "Vigente" },
      { name: "Leucemia Felina", date: "12/03/2024", vetId: "VET-56102", status: "Vigente" },
    ],
    foodMain: "Hills Science Diet Indoor Cat",
    dietType: "Mixta",
    dailyAmount: "1 taza (80g) + 1 lata humeda",
    activityLevel: "Alto",
    coexistsWithOtherPets: false,
  },
  {
    id: "3",
    name: "Max",
    species: "Perro",
    breed: "Golden Retriever",
    sex: "Macho",
    birthDate: "10/06/2021",
    age: "5 anos",
    microchip: "985112009156743",
    location: "Medellin, Colombia",
    imageUrl: "/images/max-dog.jpg",
    isServiceAnimal: true,
    isSterilized: true,
    healthStatus: "Cuidado Especial",
    allergies: "Pollo, trigo",
    medications: "Insulina 2UI cada 12h, Omeprazol 10mg diario",
    diseases: ["Diabetes", "Enfermedad cardiaca"],
    vaccines: [
      { name: "Rabia", date: "01/02/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Parvovirus", date: "01/02/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Moquillo", date: "01/02/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Bordetella", date: "10/08/2023", vetId: "VET-84729", status: "Vencida" },
      { name: "Leptospirosis", date: "01/02/2025", vetId: "VET-77301", status: "Vigente" },
    ],
    foodMain: "Pro Plan Veterinary Diets HA",
    dietType: "Pienso / Croquetas",
    dailyAmount: "3 tazas (350g)",
    activityLevel: "Bajo",
    coexistsWithOtherPets: true,
  },
  {
    id: "4",
    name: "Canela",
    species: "Perro",
    breed: "Labrador Retriever",
    sex: "Hembra",
    birthDate: "03/11/2020",
    age: "5 anos",
    microchip: "985112004523198",
    location: "Barranquilla, Colombia",
    imageUrl: "/images/canela-dog.jpg",
    isServiceAnimal: false,
    isSterilized: true,
    healthStatus: "Saludable",
    allergies: "Ninguna conocida",
    medications: "Ninguno",
    diseases: [],
    vaccines: [
      { name: "Rabia", date: "20/05/2025", vetId: "VET-42890", status: "Vigente" },
      { name: "Parvovirus", date: "20/05/2025", vetId: "VET-42890", status: "Vigente" },
      { name: "Moquillo", date: "20/05/2025", vetId: "VET-42890", status: "Vigente" },
      { name: "Leptospirosis", date: "20/05/2025", vetId: "VET-42890", status: "Vigente" },
    ],
    foodMain: "Purina Pro Plan Large Breed",
    dietType: "Pienso / Croquetas",
    dailyAmount: "2.5 tazas (300g)",
    activityLevel: "Alto",
    coexistsWithOtherPets: true,
  },
  {
    id: "5",
    name: "Michi",
    species: "Gato",
    breed: "Naranja Tabby Domestico",
    sex: "Macho",
    birthDate: "14/02/2022",
    age: "4 anos",
    microchip: "985112006789432",
    location: "Cali, Colombia",
    imageUrl: "/images/michi-cat.jpg",
    isServiceAnimal: false,
    isSterilized: true,
    healthStatus: "Saludable",
    allergies: "Lacteos",
    medications: "Ninguno",
    diseases: [],
    vaccines: [
      { name: "Triple Felina", date: "18/07/2025", vetId: "VET-19473", status: "Vigente" },
      { name: "Rabia", date: "18/07/2025", vetId: "VET-19473", status: "Vigente" },
    ],
    foodMain: "Whiskas Indoor",
    dietType: "Mixta",
    dailyAmount: "3/4 taza (60g) + pouch",
    activityLevel: "Medio",
    coexistsWithOtherPets: false,
  },
  {
    id: "6",
    name: "Rocky",
    species: "Perro",
    breed: "Boxer",
    sex: "Macho",
    birthDate: "28/07/2018",
    age: "8 anos",
    microchip: "985112001234567",
    location: "Santa Marta, Colombia",
    imageUrl: "/images/rocky-dog.jpg",
    isServiceAnimal: false,
    isSterilized: false,
    healthStatus: "Cuidado Especial",
    allergies: "Ninguna conocida",
    medications: "Carprofeno 25mg cada 12h",
    diseases: ["Displasia de cadera", "Problemas dentales"],
    vaccines: [
      { name: "Rabia", date: "05/04/2025", vetId: "VET-63012", status: "Vigente" },
      { name: "Parvovirus", date: "12/01/2023", vetId: "VET-63012", status: "Vencida" },
      { name: "Moquillo", date: "12/01/2023", vetId: "VET-63012", status: "Vencida" },
      { name: "Bordetella", date: "05/04/2025", vetId: "VET-63012", status: "Vigente" },
    ],
    foodMain: "Royal Canin Maxi Aging 8+",
    dietType: "Pienso / Croquetas",
    dailyAmount: "3 tazas (380g)",
    activityLevel: "Bajo",
    coexistsWithOtherPets: true,
  },
  {
    id: "7",
    name: "Nina",
    species: "Gato",
    breed: "Persa",
    sex: "Hembra",
    birthDate: "09/12/2017",
    age: "8 anos",
    microchip: "985112008901234",
    location: "Cartagena, Colombia",
    imageUrl: "/images/nina-cat.jpg",
    isServiceAnimal: false,
    isSterilized: true,
    healthStatus: "Cuidado Especial",
    allergies: "Ciertos conservantes alimentarios",
    medications: "Benazepril 2.5mg diario",
    diseases: ["Enfermedad renal", "Problemas oculares"],
    vaccines: [
      { name: "Triple Felina", date: "30/11/2024", vetId: "VET-84729", status: "Vigente" },
      { name: "Rabia", date: "30/11/2024", vetId: "VET-84729", status: "Vigente" },
      { name: "Leucemia Felina", date: "15/05/2022", vetId: "VET-56102", status: "Vencida" },
    ],
    foodMain: "Royal Canin Renal Feline",
    dietType: "Mixta",
    dailyAmount: "1/2 taza (45g) + lata renal",
    activityLevel: "Bajo",
    coexistsWithOtherPets: false,
  },
  {
    id: "8",
    name: "Toby",
    species: "Perro",
    breed: "Beagle",
    sex: "Macho",
    birthDate: "25/04/2024",
    age: "2 anos",
    microchip: "985112005678901",
    location: "Pereira, Colombia",
    imageUrl: "/images/toby-dog.jpg",
    isServiceAnimal: false,
    isSterilized: false,
    healthStatus: "Saludable",
    allergies: "Ninguna conocida",
    medications: "Ninguno",
    diseases: [],
    vaccines: [
      { name: "Rabia", date: "01/06/2025", vetId: "VET-35784", status: "Vigente" },
      { name: "Parvovirus", date: "01/06/2025", vetId: "VET-35784", status: "Vigente" },
      { name: "Moquillo", date: "01/06/2025", vetId: "VET-35784", status: "Vigente" },
    ],
    foodMain: "Purina Pro Plan Puppy",
    dietType: "Pienso / Croquetas",
    dailyAmount: "2 tazas (200g)",
    activityLevel: "Muy Alto",
    coexistsWithOtherPets: true,
  },
  {
    id: "9",
    name: "Cleo",
    species: "Gato",
    breed: "Bombay",
    sex: "Hembra",
    birthDate: "16/10/2021",
    age: "4 anos",
    microchip: "985112003456789",
    location: "Bucaramanga, Colombia",
    imageUrl: "/images/cleo-cat.jpg",
    isServiceAnimal: false,
    isSterilized: true,
    healthStatus: "Saludable",
    allergies: "Polen",
    medications: "Ninguno",
    diseases: [],
    vaccines: [
      { name: "Triple Felina", date: "22/08/2025", vetId: "VET-90214", status: "Vigente" },
      { name: "Rabia", date: "22/08/2025", vetId: "VET-90214", status: "Vigente" },
      { name: "Leucemia Felina", date: "22/08/2025", vetId: "VET-90214", status: "Vigente" },
    ],
    foodMain: "Acana Indoor Entrée",
    dietType: "Pienso / Croquetas",
    dailyAmount: "3/4 taza (55g)",
    activityLevel: "Alto",
    coexistsWithOtherPets: true,
  },
  {
    id: "10",
    name: "Zeus",
    species: "Perro",
    breed: "Pastor Aleman",
    sex: "Macho",
    birthDate: "02/01/2020",
    age: "6 anos",
    microchip: "985112002345678",
    location: "Cartagena, Colombia",
    imageUrl: "/images/zeus-dog.jpg",
    isServiceAnimal: true,
    isSterilized: true,
    healthStatus: "Saludable",
    allergies: "Maiz, soya",
    medications: "Ninguno",
    diseases: [],
    vaccines: [
      { name: "Rabia", date: "15/03/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Parvovirus", date: "15/03/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Moquillo", date: "15/03/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Leptospirosis", date: "15/03/2025", vetId: "VET-77301", status: "Vigente" },
      { name: "Bordetella", date: "15/03/2025", vetId: "VET-77301", status: "Vigente" },
    ],
    foodMain: "Orijen Original Dog",
    dietType: "Pienso / Croquetas",
    dailyAmount: "3.5 tazas (400g)",
    activityLevel: "Alto",
    coexistsWithOtherPets: true,
  },
]
